# Generated by Django 5.1.15 on 2026-07-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
