/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#465aa3',
        'on-primary': '#ffffff',
        'primary-container': '#EAEFFD',
        'on-primary-container': '#1e347b',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b6c4ff',
        'inverse-primary': '#b6c4ff',
        'on-primary-fixed': '#001550',
        'on-primary-fixed-variant': '#2d4289',

        secondary: '#8a5108',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdb164',
        'on-secondary-container': '#754300',
        'secondary-fixed': '#ffdcbe',
        'secondary-fixed-dim': '#ffb871',
        'on-secondary-fixed': '#2d1600',
        'on-secondary-fixed-variant': '#6a3c00',

        tertiary: '#116b51',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#E5FAF1',
        'on-tertiary-container': '#1F8A5F',
        'tertiary-fixed': '#a2f3d1',
        'tertiary-fixed-dim': '#87d6b6',
        'on-tertiary-fixed': '#002116',
        'on-tertiary-fixed-variant': '#00513b',

        error: '#E2737A',
        'on-error': '#ffffff',
        'error-container': '#FCEAEC',
        'on-error-container': '#93000a',

        background: '#faf8ff',
        'on-background': '#1b1b20',
        surface: '#FBFBFF',
        'on-surface': '#34406E',
        'on-surface-variant': '#444651',
        'surface-variant': '#e3e1e8',
        'surface-tint': '#465aa3',
        'surface-dim': '#dbd9e0',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3fa',
        'surface-container': '#FFFFFF',
        'surface-container-high': '#e9e7ee',
        'surface-container-highest': '#e3e1e8',

        outline: '#E6E9F7',
        'outline-variant': '#c5c5d2',

        'inverse-surface': '#2f3035',
        'inverse-on-surface': '#f2f0f7',

        'text-primary': '#1b1b20',
        'text-secondary': '#444651',
        'status-mint': '#116b51',
        'danger-red': '#E2737A',

        'admin-primary': '#ff6b00',
        'admin-on-primary': '#ffffff',
        'admin-secondary': '#2563eb',
        'admin-on-secondary': '#ffffff',
        'admin-secondary-container': '#dbeafe',
        'admin-on-secondary-container': '#1e3a8a',
        'admin-surface': '#f9f9f7',
        'admin-on-surface': '#1c1b1f',
        'admin-on-surface-variant': '#49454f',
        'admin-surface-container-lowest': '#ffffff',
        'admin-surface-container-low': '#f4f4f2',
        'admin-surface-container': '#eeeede',
        'admin-surface-container-high': '#e8e8e6',
        'admin-outline': '#79747e',
        'admin-outline-variant': '#dadada',
        'admin-error': '#ba1a1a',
        'admin-primary-container': '#ffeadb',
        'admin-on-primary-container': '#3a1500',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '16px',
        '2xl': '20px',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        gutter: '24px',
        xs: '8px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        '2xl': '64px',
        base: '4px',
      },
      fontFamily: {
        'display-lg': ['Space Grotesk'],
        'headline-lg': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
        'headline-sm': ['Space Grotesk'],
        'title-lg': ['Space Grotesk'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-lg': ['JetBrains Mono'],
        'label-md': ['JetBrains Mono'],
        'label-sm': ['JetBrains Mono'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      boxShadow: {
        sm: '0 1px 3px rgba(90,107,196,.08)',
        md: '0 8px 20px rgba(90,107,196,.12)',
        lg: '0 18px 44px rgba(90,107,196,.16)',
      },
    },
  },
  plugins: [],
}
