# Generated by Django 4.2.30 on 2026-07-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="questions/images/"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="retake_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
