# Generated by Django 5.0.14 on 2026-06-20 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('downloaded_at', models.DateTimeField()),
                ('scheduled_deletion_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledFileDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('delete_after', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['delete_after', 'deleted'], name='pipeline_sc_delete__e70928_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exam_date', '-score'],
                'indexes': [models.Index(fields=['exam_date'], name='pipeline_da_exam_da_da2e53_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyscore',
            constraint=models.UniqueConstraint(fields=('student', 'exam_date'), name='unique_student_exam_date_score'),
        ),
    ]
